export enum UserQueryKeys {
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_USER = 'GET_USER',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
  GET_ALL_USERS = 'GET_ALL_USERS',

  // ** Follow Mutations ** //
  GET_USER_FOLLOWERS = 'GET_USER_FOLLOWERS',
  GET_USER_FOLLOWINGS = 'GET_USER_FOLLOWINGS',
  FOLLOW_USER = 'FOLLOW_USER',
  UNFOLLOW_USER = 'UNFOLLOW_USER',
  BLOCK_USER = 'BLOCK_USER',
  FOLLOW_STATUS = 'FOLLOW_STATUS',
}
