import { strict as assert } from 'assert';
import dotenv from 'dotenv';
import { load } from 'ts-dotenv';

// Load the .env file
dotenv.config();

// Load jwt environment variables
const jwtSchema = load({
  JWT_ADMIN_SECRET: String,
  JWT_REFRESH_ADMIN_SECRET: String,
  JWT_REFRESH_ADMIN_EXPIRES_IN: String,
  JWT_EXPIRES_IN: String,
  JWT_ADMIN_MAX_AGE: Number,
  JWT_COOKIE_EXPIRES_IN_ADMIN_REGISTRATION: String,
  JWT_COOKIE_EXPIRES_IN: String,
  JWT_COOKIE_SECURE: Boolean,
  JWT_COOKIE_HTTP_ONLY: Boolean,
  JWT_SAME_SITE: String,
  JWT_ADMIN_COOKIE_NAME: String,
  JWT_ISSUER: String,
});

const {
  JWT_ADMIN_SECRET,
  JWT_REFRESH_ADMIN_SECRET,
  JWT_REFRESH_ADMIN_EXPIRES_IN,
  JWT_EXPIRES_IN,
  JWT_ADMIN_MAX_AGE,
  JWT_COOKIE_EXPIRES_IN_ADMIN_REGISTRATION,
  JWT_COOKIE_EXPIRES_IN,
  JWT_COOKIE_SECURE,
  JWT_COOKIE_HTTP_ONLY,
  JWT_SAME_SITE,
  JWT_ADMIN_COOKIE_NAME,
  JWT_ISSUER,
} = jwtSchema;

assert(JWT_ADMIN_SECRET, 'JWT_SECRET  is required');
assert(JWT_REFRESH_ADMIN_SECRET, 'JWT  REFRESH SECRET is required');
assert(
  JWT_REFRESH_ADMIN_EXPIRES_IN,
  'JWT_REFRESH_ADMIN_EXPIRES_IN is required'
);
assert(JWT_EXPIRES_IN, 'JWT_EXPIRES_IN is required');
assert(JWT_ADMIN_MAX_AGE, 'JWT_ADMIN_MAX_AGES is required');
assert(
  JWT_COOKIE_EXPIRES_IN_ADMIN_REGISTRATION,
  'JWT_COOKIE_EXPIRES_IN_ADMIN_REGISTRATION is required'
);
assert(JWT_COOKIE_EXPIRES_IN, 'JWT_COOKIE_EXPIRES_IN is required');
assert(JWT_COOKIE_SECURE, 'JWT_COOKIE_SECURE is required');
assert(JWT_COOKIE_HTTP_ONLY, 'JWT_COOKIE_HTTP_ONLY is required');
assert(JWT_SAME_SITE, 'JWT_SAME_SITE is required');
assert(JWT_ADMIN_COOKIE_NAME, 'JWT_ADMIN_COOKIE_NAME is required');
assert(JWT_ISSUER, 'JWT_ISSUER is required');

export const jwtAdminENV = {
  JWT_ADMIN_SECRET,
  JWT_REFRESH_ADMIN_SECRET,
  JWT_EXPIRES_IN,
  JWT_REFRESH_ADMIN_EXPIRES_IN,
  JWT_ADMIN_MAX_AGE,
  JWT_COOKIE_EXPIRES_IN_ADMIN_REGISTRATION,
  JWT_COOKIE_EXPIRES_IN,
  JWT_COOKIE_SECURE,
  JWT_COOKIE_HTTP_ONLY,
  JWT_SAME_SITE,
  JWT_ADMIN_COOKIE_NAME,
  JWT_ISSUER,
};

export default {
  jwtAdminENV,
  JWT_ADMIN_SECRET,
  JWT_REFRESH_ADMIN_SECRET,
  JWT_REFRESH_ADMIN_EXPIRES_IN,
  JWT_EXPIRES_IN,
  JWT_ADMIN_MAX_AGE,
  JWT_COOKIE_EXPIRES_IN_ADMIN_REGISTRATION,
  JWT_COOKIE_EXPIRES_IN,
  JWT_COOKIE_SECURE,
  JWT_COOKIE_HTTP_ONLY,
  JWT_SAME_SITE,
  JWT_ADMIN_COOKIE_NAME,
  JWT_ISSUER,
};
