export enum UploadQueryKeys {
  // Get preview image
  GET_IMAGE_PREVIEW = 'GET_IMAGE_PREVIEW',
  GET_PROFILE_PIC_PREVIEW = 'GET_PROFILE_PIC_PREVIEW',
  GET_USER_STORY_PREVIEW = 'GET_USER_STORY_PREVIEW',
}
