export enum PostQueryKeys {
  GET_INFITE_POSTS = 'GET_INFITE_POSTS',
  GET_POST_BY_ID = 'GET_POST_BY_ID',
  GET_RECENT_POSTS = 'GET_RECENT_POSTS',
  GET_ALL_POSTS = 'GET_ALL_POSTS',
  SAVE_POST = 'SAVE_POST',
}
