export enum StoryQueryKeys {
  FETCH_USER_STORIES = 'FETCH_USER_STORIES',
  FETCH_USER_STORY = 'FETCH_USER_STORY',
  UPDATE_USER_STORY = 'UPDATE_USER_STORY',
  FETCH_SELF_STORY = 'FETCH_SELF_STORY',
}
